[project]
name = "conductor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langgraph>=0.2.19",
    "peewee>=3.17.6",
    "pyppeteer>=2.0.0",
    "ruff>=0.6.4",
]
